translation guidance from data standard readme added
openownership/bods-dev-handbook pull request #43
Opened 2022-06-22 15:15 UTC by lgs85

Resolves issue [398](https://github.com/openownership/data-standard/issues/398) from the data standard repo. Note that I haven't done a full edit of the guidance, but have just added the text from the data standard readme and removed from there. Also had to change various hyperlinks etc and slightly alter structure to make it readable with the new section added

2022-06-27 11:52 UTC, kd-ods commented
@lgs85 - these changes all look good to me, but I think we should ask for final approval from @siwhitehouse.

(@siwhitehouse - I suspect that you'll be able to OK these at a glance, or at least on a '...good enough... safe enough...' basis.)

2022-07-27 15:26 UTC, siwhitehouse requested changes
Hi @lgs85 - apologies for the delay. I've just got the one comment which is that setting up a new project should go before the translation workflow as the workflow depends on this being done.

2022-07-27 15:57 UTC, siwhitehouse commented on translations.md
> +### Translation workflow
Thanks @lgs85

2022-07-27 15:57 UTC, siwhitehouse approved these changes

2022-07-27 15:58 UTC, merged