Update to reflect refactored tests
openownership/bods-dev-handbook pull request #58
Opened 2024-02-20 10:59 UTC by rhiaro

2024-03-05 10:19 UTC, BibianaC commented on testing.md
> +            "entityType": "unknownEntity",
Wouldn't this only be the case with "entity" statements?

2024-03-05 12:40 UTC, kd-ods requested changes
A few suggestions.

2024-03-05 12:40 UTC, kd-ods commented on testing.md
> +Start from this, and add only the field you are testing. If you are testing a field in a nested object (eg. `publicationDetails/publisher/name`) you may need to add more data to cover additional requ
```suggestion
Start from a minimal statement like this, and add only the field you are testing. If you are testing a field in a nested object (eg. `publicationDetails/publisher/name`) you may need to add more data to cover additional required fields (eg. `publicationDetails/publicationDate`). Check the schema itself to find out which fields are required for the various objects.
```

2024-03-05 12:40 UTC, kd-ods commented on testing.md
> +After adding new files make sure **run the tests** (`pytest tests/test_data.py`) to check they pass.
```suggestion
After adding new files make sure to **run the tests** (`pytest tests/test_data.py`) to check they pass.
```

2024-03-07 09:59 UTC, kd-ods approved these changes
Great.

2024-03-07 15:08 UTC, merged